In [46]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import MaxAbsScaler
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.feature_extraction.text import TfidfVectorizer

CountVectorizer + LogisticRegression

In [37]:
df = pd.read_csv("df_key_rate.csv")

x_train, x_test, y_train, y_test = train_test_split(df.text, df.target, random_state=42)

vec = CountVectorizer(ngram_range=(1,1))
bow = vec.fit_transform(x_train)
bow_test = vec.transform(x_test)

scaler = MaxAbsScaler()
bow = scaler.fit_transform(bow)
bow_test = scaler.transform(bow_test)


clf = LogisticRegression(max_iter=200, random_state=42)
clf.fit(bow, y_train)
pred = clf.predict(bow_test)
print(classification_report(y_test, pred))

f1_macro_cv_1g = f1_score(y_test, pred, average='macro')
print(f"F1 macro: {f1_macro_cv_1g:.2f}")

              precision    recall  f1-score   support

        -1.0       0.75      0.92      0.83        13
         0.0       0.75      0.75      0.75         8
         1.0       1.00      0.40      0.57         5

    accuracy                           0.77        26
   macro avg       0.83      0.69      0.72        26
weighted avg       0.80      0.77      0.75        26

F1 macro: 0.72

In [42]:
results_df = pd.DataFrame(columns=["model", "f1_macro"])

results_df.loc[len(results_df)] = {
    "model": "CountVectorizer(1gramm) + LogisticRegression",
    "f1_macro": f1_macro_cv_1g
}
results_df

                                          model  f1_macro
0  CountVectorizer(1gramm) + LogisticRegression  0.716338

In [39]:
vec = CountVectorizer(ngram_range=(1, 3))
bow = vec.fit_transform(x_train)
bow_test = vec.transform(x_test)


scaler = MaxAbsScaler()
bow = scaler.fit_transform(bow)
bow_test = scaler.transform(bow_test)

clf = LogisticRegression(max_iter=200, random_state=42)
clf.fit(bow, y_train)
pred_thrgramm = clf.predict(bow_test)
print(classification_report(y_test, pred_thrgramm))

f1_macro_cv_3g = f1_score(y_test, pred_thrgramm, average='macro')
print(f"F1 macro: {f1_macro_cv_3g:.2f}")

              precision    recall  f1-score   support

        -1.0       0.71      0.92      0.80        13
         0.0       0.75      0.75      0.75         8
         1.0       1.00      0.20      0.33         5

    accuracy                           0.73        26
   macro avg       0.82      0.62      0.63        26
weighted avg       0.78      0.73      0.69        26

F1 macro: 0.63

In [43]:
results_df.loc[len(results_df)] = {
    "model": "CountVectorizer(1-3gramm) + LogisticRegression",
    "f1_macro": f1_macro_cv_3g
}
results_df

                                            model  f1_macro
0    CountVectorizer(1gramm) + LogisticRegression  0.716338
1  CountVectorizer(1-3gramm) + LogisticRegression  0.627778

TfidfVectorizer + LogisticRegression

In [51]:
vec = TfidfVectorizer(ngram_range=(1, 1))
vec_train = vec.fit_transform(x_train)
vec_test = vec.transform(x_test)


scaler = MaxAbsScaler()
vec_train = scaler.fit_transform(vec_train)
vec_test = scaler.transform(vec_test)

clf = LogisticRegression(max_iter=200, random_state=42)
clf.fit(vec_train, y_train)
pred_tfidf_1g = clf.predict(vec_test)
print(classification_report(y_test, pred_tfidf_1g))

f1_macro_tfidf_1g = f1_score(y_test, pred_tfidf_1g, average='macro')
print(f"F1 macro: {f1_macro_tfidf_1g:.2f}")

              precision    recall  f1-score   support

        -1.0       0.80      0.92      0.86        13
         0.0       0.71      0.62      0.67         8
         1.0       1.00      0.80      0.89         5

    accuracy                           0.81        26
   macro avg       0.84      0.78      0.80        26
weighted avg       0.81      0.81      0.80        26

F1 macro: 0.80

In [49]:
results_df.loc[len(results_df)] = {
    "model": "TfidfVectorizer(1gramm) + LogisticRegression",
    "f1_macro": f1_macro_tfidf_1g
}
results_df

                                            model  f1_macro
0    CountVectorizer(1gramm) + LogisticRegression  0.716338
1  CountVectorizer(1-3gramm) + LogisticRegression  0.627778
2    TfidfVectorizer(1gramm) + LogisticRegression  0.804233

In [52]:
vec = TfidfVectorizer(ngram_range=(1, 3))
vec_train = vec.fit_transform(x_train)
vec_test = vec.transform(x_test)


scaler = MaxAbsScaler()
vec_train = scaler.fit_transform(vec_train)
vec_test = scaler.transform(vec_test)

clf = LogisticRegression(max_iter=200, random_state=42)
clf.fit(vec_train, y_train)
pred_tfidf_3g = clf.predict(vec_test)
print(classification_report(y_test, pred_tfidf_3g))

f1_macro_tfidf_3g = f1_score(y_test, pred_tfidf_3g, average='macro')
print(f"F1 macro: {f1_macro_tfidf_3g:.2f}")

              precision    recall  f1-score   support

        -1.0       0.67      0.92      0.77        13
         0.0       0.71      0.62      0.67         8
         1.0       1.00      0.20      0.33         5

    accuracy                           0.69        26
   macro avg       0.79      0.58      0.59        26
weighted avg       0.75      0.69      0.66        26

F1 macro: 0.59

In [53]:
results_df.loc[len(results_df)] = {
    "model": "TfidfVectorizer(1-3gramm) + LogisticRegression",
    "f1_macro": f1_macro_tfidf_3g
}
results_df

                                            model  f1_macro
0    CountVectorizer(1gramm) + LogisticRegression  0.716338
1  CountVectorizer(1-3gramm) + LogisticRegression  0.627778
2    TfidfVectorizer(1gramm) + LogisticRegression  0.804233
3  TfidfVectorizer(1-3gramm) + LogisticRegression  0.591398

In [54]:
results_df.to_csv("results_df.csv", index=False)